### ISSUE TITLE
if timestamp column has a default value,  then error occurred.

### ISSUE THREAD

**Issue by bsshin71** [aminkr/UTCTimestampConverter#2]
1. error stack
org.apache.kafka.connect.errors.SchemaBuilderException: Invalid SchemaBuilder call: default has already been set.
        at org.apache.kafka.connect.data.SchemaBuilder.checkCanSet(SchemaBuilder.java:437)
        at org.apache.kafka.connect.data.SchemaBuilder.defaultValue(SchemaBuilder.java:126)
        at io.debezium.relational.TableSchemaBuilder.addField(TableSchemaBuilder.java:380)
        at io.debezium.relational.TableSchemaBuilder.lambda$create$2(TableSchemaBuilder.java:119)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at io.debezium.relational.TableSchemaBuilder.create(TableSchemaBuilder.java:117)
        at io.debezium.relational.RelationalDatabaseSchema.buildAndRegisterSchema(RelationalDatabaseSchema.java:130)
        at io.debezium.connector.mysql.MySqlSchema.lambda$refreshSchemas$3(MySqlSchema.java:297)
        at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4698)
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
        at io.debezium.connector.mysql.MySqlSchema.refreshSchemas(MySqlSchema.java:295)
        at io.debezium.connector.mysql.MySqlSchema.loadHistory(MySqlSchema.java:270)
        at io.debezium.connector.mysql.MySqlTaskContext.loadHistory(MySqlTaskContext.java:164)
        at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:110)
        at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:106)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:232)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

2. my connector configuration is the following.
    "connector.class": "io.debezium.connector.mysql.MySqlConnector",
    "tasks.max": "1",
	"database.server.name": "mysql", 
    "database.include.list": "DB",
	"table.include.list": 	"DB.T1,DB.T2,DB.T3,DB.T4",
    "database.history.kafka.bootstrap.servers": "localhost:9092",
    "database.history.kafka.topic": "topic-mysql",
    "include.schema.changes": "true",
    "snapshot.mode": "schema_only",
    "transforms": "route,unwrap",
    "transforms.route.type": "org.apache.kafka.connect.transforms.RegexRouter",
    "transforms.route.regex": "([^.]+)\\.([^.]+)\\.([^.]+)",
    "transforms.route.replacement": "$3",
	"transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
	"transforms.unwrap.drop.tombstones": "false",
	"transforms.unwrap.delete.handling.mode": "none",
	"key.converter.schema.registry.url": "http://localhost:8081",
	"value.converter.schema.registry.url": "http://localhost:8081",
    "key.converter": "io.confluent.connect.avro.AvroConverter",
	"value.converter": "io.confluent.connect.avro.AvroConverter",
	"converters": "timestampConverter",
	"timestampConverter.type": "snapp.kafka.connect.util.UTCTimestampConverter"

**Comment by bsshin71** [comment]
how can I avoid the above errors,   thanks  for your effort.

**Comment by aminkr** [comment]
I have changed the functionality of the code in the last commit. Can you check the last commit and let me know if you have still the same problem?

**Comment by aminkr** [comment]
> how can I avoid the above errors, thanks for your effort.

I have changed some part of the code in the last commit. Can you check the last commit and let me know if you have still the same problem?

**Comment by bsshin71** [comment]
thank you so much,  it work well,  ^^
I owe you a lot.  I pray that you'll be happy
